name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Presentation Build"]
    types: [completed]
    branches: [main]

# Sets permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Prepare Deployment
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download presentation artifacts
        uses: actions/download-artifact@v4
        with:
          name: presentation-pdfs
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare deployment directory
        run: |
          mkdir -p deploy
          mv presentation.pdf deploy/
          mv presentation-handout.pdf deploy/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

  deploy:
    name: Deploy to Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
